// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppFinal.Models;

#nullable disable

namespace WebAppFinal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251125145941_DirtBikeUpdate")]
    partial class DirtBikeUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAppFinal.Models.DirtBike", b =>
                {
                    b.Property<int>("DirtBikeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DirtBikeId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Displacement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DirtBikeId");

                    b.ToTable("DirtBikes");

                    b.HasData(
                        new
                        {
                            DirtBikeId = 1,
                            Description = "This was my first introduction to dirt bikes, I have great memories of riding this bike around my parents front yard. They probably didn't like all the tracks it left in the yard.",
                            Displacement = "80cc",
                            Make = "Honda",
                            Model = "CR80",
                            Year = "1998"
                        },
                        new
                        {
                            DirtBikeId = 2,
                            Description = "My second bike. This one was not as thrilling as the previous. CR80, but my CR80 ended up blowing up and at the time, I didn't have the knowledge or funds to repair it. The XR100 was still a good bike, but I was beginning to get too big for it.",
                            Displacement = "100cc",
                            Make = "Honda",
                            Model = "XR100",
                            Year = "2004"
                        },
                        new
                        {
                            DirtBikeId = 3,
                            Description = "This was my first 'full size' bike. This bike had much more power than the previous XR100, but it wasn't crazy fast by any means. I was just happy to have a bigger bike at this point.",
                            Displacement = "200cc",
                            Make = "Honda",
                            Model = "XR200",
                            Year = "2002"
                        },
                        new
                        {
                            DirtBikeId = 4,
                            Description = "This bike was a step up from the XR200, but for whatever reason it wasn't very reliable so I ended up selling it pretty quickly.",
                            Displacement = "250cc",
                            Make = "Honda",
                            Model = "XR250R",
                            Year = "1999"
                        },
                        new
                        {
                            DirtBikeId = 5,
                            Description = "This bike was very fun but it didn't have much torque which became a problem since I mostly rode it in areas with steep hills and tight trails.",
                            Displacement = "125cc",
                            Make = "Honda",
                            Model = "CR125",
                            Year = "2001"
                        },
                        new
                        {
                            DirtBikeId = 6,
                            Description = "This my first 'Fast' bike. I had a lot of fun on it but it wasn't in the best shape when I bought it so it didn't last long before it started having issues.",
                            Displacement = "250cc",
                            Make = "Kawasaki",
                            Model = "KX250",
                            Year = "1999"
                        },
                        new
                        {
                            DirtBikeId = 7,
                            Description = "My current bike. I purchased it from a guy that took great care of it and it runs great. I've had it for 4 years now and it's never let me down. I plan to keep this bike for a long time and rebuild it when the time comes.",
                            Displacement = "250cc",
                            Make = "Yamaha",
                            Model = "YZ250",
                            Year = "2004"
                        });
                });

            modelBuilder.Entity("WebAppFinal.Models.DistanceRunning", b =>
                {
                    b.Property<int>("DistanceRunningId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistanceRunningId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("Distance")
                        .HasColumnType("float");

                    b.Property<int>("MaxHeartRate")
                        .HasColumnType("int");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.HasKey("DistanceRunningId");

                    b.ToTable("DistanceRunnings");

                    b.HasData(
                        new
                        {
                            DistanceRunningId = 1,
                            Date = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Distance = 5.2000000000000002,
                            MaxHeartRate = 165,
                            Time = 45
                        },
                        new
                        {
                            DistanceRunningId = 2,
                            Date = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Distance = 8.5,
                            MaxHeartRate = 172,
                            Time = 72
                        },
                        new
                        {
                            DistanceRunningId = 3,
                            Date = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Distance = 10.0,
                            MaxHeartRate = 178,
                            Time = 88
                        },
                        new
                        {
                            DistanceRunningId = 4,
                            Date = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Distance = 6.7999999999999998,
                            MaxHeartRate = 168,
                            Time = 58
                        },
                        new
                        {
                            DistanceRunningId = 5,
                            Date = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Distance = 12.0,
                            MaxHeartRate = 180,
                            Time = 105
                        });
                });

            modelBuilder.Entity("WebAppFinal.Models.VideoGame", b =>
                {
                    b.Property<int>("VideoGameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VideoGameId"));

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Platforms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("VideoGameId");

                    b.ToTable("VideoGames");

                    b.HasData(
                        new
                        {
                            VideoGameId = 1,
                            Genre = "Platformer",
                            Platforms = "Nintendo 64",
                            Rating = 3.5,
                            ReleaseDate = new DateTime(1996, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            VideoGameId = 2,
                            Genre = "Platformer",
                            Platforms = "PC",
                            Rating = 5.0,
                            ReleaseDate = new DateTime(2011, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
