// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppFinal.Models;

#nullable disable

namespace WebAppFinal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAppFinal.Models.DirtBike", b =>
                {
                    b.Property<int>("DirtBikeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DirtBikeId"));

                    b.Property<string>("Displacement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DirtBikeId");

                    b.ToTable("DirtBikes");

                    b.HasData(
                        new
                        {
                            DirtBikeId = 1,
                            Displacement = "249cc",
                            Make = "Honda",
                            Model = "CR250",
                            Year = "1995"
                        },
                        new
                        {
                            DirtBikeId = 2,
                            Displacement = "249cc",
                            Make = "Yamaha",
                            Model = "YZ250",
                            Year = "2004"
                        },
                        new
                        {
                            DirtBikeId = 3,
                            Displacement = "249cc",
                            Make = "Suzuki",
                            Model = "RM250",
                            Year = "1999"
                        });
                });

            modelBuilder.Entity("WebAppFinal.Models.DistanceRunning", b =>
                {
                    b.Property<int>("DistanceRunningId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistanceRunningId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("Distance")
                        .HasColumnType("float");

                    b.Property<int>("MaxHeartRate")
                        .HasColumnType("int");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.HasKey("DistanceRunningId");

                    b.ToTable("DistanceRunnings");

                    b.HasData(
                        new
                        {
                            DistanceRunningId = 1,
                            Date = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Distance = 5.2000000000000002,
                            MaxHeartRate = 165,
                            Time = 45
                        },
                        new
                        {
                            DistanceRunningId = 2,
                            Date = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Distance = 8.5,
                            MaxHeartRate = 172,
                            Time = 72
                        },
                        new
                        {
                            DistanceRunningId = 3,
                            Date = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Distance = 10.0,
                            MaxHeartRate = 178,
                            Time = 88
                        },
                        new
                        {
                            DistanceRunningId = 4,
                            Date = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Distance = 6.7999999999999998,
                            MaxHeartRate = 168,
                            Time = 58
                        },
                        new
                        {
                            DistanceRunningId = 5,
                            Date = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Distance = 12.0,
                            MaxHeartRate = 180,
                            Time = 105
                        });
                });

            modelBuilder.Entity("WebAppFinal.Models.VideoGame", b =>
                {
                    b.Property<int>("VideoGameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VideoGameId"));

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Platforms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("VideoGameId");

                    b.ToTable("VideoGames");

                    b.HasData(
                        new
                        {
                            VideoGameId = 1,
                            Genre = "Platformer",
                            Platforms = "Nintendo 64",
                            Rating = 3.5,
                            ReleaseDate = new DateTime(1996, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            VideoGameId = 2,
                            Genre = "Platformer",
                            Platforms = "PC",
                            Rating = 5.0,
                            ReleaseDate = new DateTime(2011, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
